#!/bin/bash

# JupyterLab + Binder: Demonstrating how to get JupyterLab working with Binder 
# https://github.com/binder-examples/jupyterlab
# Widgets. Should already be enabled.
#jupyter labextension install @jupyter-widgets/jupyterlab-manager
#jupyter nbextension enable --py widgetsnbextension --sys-prefix

# Notebooks w/ extensions that auto-run code must be "trusted" to work the first time
jupyter trust CPMG_NMR_relax_interactive.ipynb

# relax
mkdir -p $HOME/software
cd $HOME/software
git clone https://github.com/nmr-relax/relax.git relax
cd $HOME/software/relax
git pull
scons
./relax -i 